name = "Qutilities"
uuid = "144146ce-868b-5e43-9e5b-0e94f26a569f"
authors = ["Dmitri Iouchtchenko <diouchtc@uwaterloo.ca>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
